apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: carts
  annotations:
    github.com/project-slug: deviousops/carts
spec:
  type: other
  lifecycle: experimental
  owner: deviousops
